### ISSUE TITLE
As a meal prepper I want to be able to search for recipes so that I can get ideas for what meals to cook and eat after my workouts

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#103]
Acceptance Tests: 

TEST VALID INPUTS: "chicken", "pizza", "pasta"
1. Go to recipe page
2. Search for a valid recipe: "chicken", "pizza", "pasta"
3. Recipes relating to the keyword should be displayed,
4. Each recipe should have an individua, unique, picture of the dish. 
5. Clicking on "instructions" should open a new tab explaining how to make the dish.
6. Calories of the dish are also shown. 

TEST INVALID INPUT: "123412894318y5ajnsdkascnb"
1. Go to recipe page
2. Search for an invalid recipe: "123412894318y5ajnsdkascnb"
3. If there are no results, the user should be notified that nothing was found.
4. Searching for a valid food should still work (invalid API call should not break the page for future searches)

**Comment by louismot** [comment]
What happens when an invalid input is entered like "rock," or a valid input like "turkey" that has no available recipes.
