### ISSUE TITLE
UI for recipe search functionality

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#104]
Task Tests: 

INPUT: "chicken"
1. Go to the recipe page
2. The background should be blue
3. The search bar should be visible and styled with CSS.
4. The search bar should be responsive.
5. Search for "chicken"
6. The results should be responsive. There should be at most 3 results in each row. Resizing the window properly moves the results to fit 2 in a row (if possible), and 1 in a row (mobile). 

INPUT: "pasta"
1. Repeat the above steps but search for "pasta" instead.\
2. Verify the images are different than those displayed when "chicken" was searched. 
3. Verify the links/redirects are different than those when "chicken" was searched.
***See task#119 for invalid inputs***

**Comment by louismot** [comment]
This needs to be added as a dependency for a story.
