### ISSUE TITLE
get app id and API key for recipe search functionality

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#105]
Task Tests: 
1. Go to the "recipes.js" file
2. The application ID should be assigned to a variable. 
3. The application key should be assigned to a variable. 
4. Both of these values should match the values given on "https://developer.edamam.com/" in our account section. 
**See discord for login information**

line 4, 5 in recipes.js: 
let application_id = "699e029b",
     api_key = "ab4351cc5633793a3a988e97472b6735";

**Comment by louismot** [comment]
This needs to be added as a dependency for a story.
