### ISSUE TITLE
Record user input of the requested recipe search

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#106]
Task Tests: 

INPUT: "chicken" (input with expected results)
1. Go to the recipes page
2. Search for "chicken"
3. Go to the browser console (right click > inspect > console)
4. The user's search should be printed to the console on search submission. 
        - "User searched for: 'chicken'" 

INPUT: "12315465ajkhca" (input with 0 expected results)
1. Go to the recipes page
2. Search for "12315465ajkhca"
3. Go to the browser console (right click > inspect > console)
4. The user's search should be printed to the console on search submission. 
        - "User searched for: '12315465ajkhca'"

**Comment by louismot** [comment]
What if the user inputs something unexpected?

Also, this needs to be added as a dependency for a story.
