### ISSUE TITLE
Call to the recipe database

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#107]
Task Tests: 
INPUT: "chicken"
1. Go to the recipes page.
2. Search for a valid recipe: "chicken"
3. Go to the browser console (right click > inspect  > console)
4. Under "Full response from API: " should be an expandable object with the information returned by the API.
5. The number of unique recipes is also displayed in the console, and should match the count in the returned object. 

INPUT: "123901874500195"
1. Repeat above with an invalid recipe: "123901874500195"
2. Go to the browser console
3. Under "Full response from API: " should be an expandable object with "count: 0". 
4. "0 unique recipes returned" should be displayed in the console.

**Comment by louismot** [comment]
Tasks should be a dependency for a story.
