### ISSUE TITLE
Save results from api call 

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#111]
Task Tests: 
 
INPUT: "chicken" (search with expected results)
1. Go to the recipes page
2. Search for "chicken"
3. Go to the console browser (right click > inspect > console)
4. Under "Full response from API call: " will be the results that were saved from the call to the API. 

INPUT: "09812031020901" (search with 0 expected results)
1. Go to the recipes page
2. Search for "09812031020901"
3. Go to the console browser (right click > inspect > console)
4. Under "Full response from API call: " will be the results that were saved from the call to the API. The object will have "0" in the count field, with no recipes available.

**Comment by louismot** [comment]
Be more specific with what your api call is. Where is it calling? What is it calling? Results of what?

Also, This needs to be added as a dependency to a story.
