### ISSUE TITLE
Display recipe results on a VALID search

### ISSUE THREAD

**Issue by ngstokes-code** [UB-CSE/course-project-a3-massive-muscles#118]
Task Tests

INPUT: "chicken"
1. Go to recipe search page
2. Search for "chicken"... Recipes should be displayed to the browser.
3. Verify each recipe has a different (relevant) picture and different calorie values 
4. Verify each recipe has a unique link to a page instructing how to make that dish. 
5. Verify the results are responsive (At most 3 to a row, then 2 to a row, then 1 to a row)

INPUT: "pizza"
1. Go to recipe search page
2. Search for "pizza"... Recipes should be displayed to the browser.
3. Verify each recipe has pictures different to those when "chicken" was searched
4. Verify each recipe has a unique link to a page instructing how to make that dish, and the links are different than those when "chicken" was searched.
5. Verify the results are responsive.

***See task#119 for invalid searches***

**Comment by louismot** [comment]
What is expected on an invalid input?

Also, this needs to be added as a dependency for a story.
