### ISSUE TITLE
As an advertiser, I want to be able to track the person using the app so I can obtain useful data to perform inferences on.

### ISSUE THREAD

**Issue by eadwu** [UB-CSE/course-project-a3-massive-muscles#64]
Acceptance Test:
(1) Have a unique identifier to identify users
(2) Lookup data in a database or query through API (/web/api/statistics[/<user_id>], /web/api/metrics)
(3) Revel in the data we track off users

Statistics stored (server-side):
- User agent
- User ID (if logged in)
- Protocol
- URL + Path

**Comment by louismot** [comment]
What specific data should be tracked? A list of types of collected data (if it isn't a massive list) would fit well here.
