### ISSUE TITLE
Store statistics identified by the user

### ISSUE THREAD

**Issue by eadwu** [UB-CSE/course-project-a3-massive-muscles#66]
Task Test
(1) Open the database storing statistics
(2) Pinpoint a specific user (if exists) and/or view the stored statistics

Possible [request] statistics
- User Agent
- Request Latency
- URL request
- Request Method

**Comment by louismot** [comment]
I think you should go a little further in-depth with your ****task tasks***. For example, what do you mean by "mine" data? Is there any private data to consider? etc
