### ISSUE TITLE
update the user text data

### ISSUE THREAD

**Issue by abdulla-abbadi** [UB-CSE/course-project-a3-massive-muscles#97]
for: story: #96
----------------
Task tests:
- For all data make sure that the data is filtered before applied
- change username
    - verify that the user changed their username by checking:
        - The new username is not associated with other user
             - If associated with other user it should print an error saying that the username is associated with other user  
        - The new username is updated in the profile and the old username is gone.
- change email
    - verify that the user changed their email by checking:
        - The new email is not associated with other user
             - If associated with other user it should print an error saying that the email used is associated with other user  
        - checking that the old email won't log the user in 
        - The new email will allow the user to login 
        - The new email is updated in the profile and the old email is gone.
- change password
    - verify that the user changed their password by:
        - checking that the old password won't log the user in 
        - The new password will allow the user to login 
- change about
    - verify that the user changed their about by checking:
        - That the old about is update in the profile page
        - The new update is persistent after login out

**Comment by louismot** [comment]
Good looking tests.
