### ISSUE TITLE
Update the user profile picture

### ISSUE THREAD

**Issue by abdulla-abbadi** [UB-CSE/course-project-a3-massive-muscles#98]
for: story: #96
----------------
Task tests:
- Change profile picture 
    - Verify that the user profile picture is changed.
        - By going to the profile page and checking that the user profile picture has changed and the old picture is not used.
    - When uploading new picture it won't allow the user to upload any types except for jpg, jpeg and png (for security reasons)
        - Upload a file that is not acceptable and it should print an error
    - When uploading new picture it should adjust the size to 250 by 250 pixels 
        - Open the photo in a another tap and the photo size should be size is 250 by 250 pixels

**Comment by abdulla-abbadi** [comment]
for: story#96
----------------
Task tests:
- Change profile picture 
    - Verify that the user profile picture is changed.
    - Verify that the user old profile picture is deleted from the system.
    - When uploading new picture it won't allow the user to upload any types except for jpg or png (for security reasons)

**Comment by louismot** [comment]
Make sure to add some task tests to this issue.
